#!/bin/bash

# Install react dependencies
npm install

# Run npm build command against 'portfolio' app
# Appspec should have moved files into /home/ec2-user

npm --prefix /home/ec2-user run build

# Empty contents of /var/www
rm -rf /var/www/*

# Move build contents to /var/www folder where nginx will serve content
mv /home/ec2-user/build/*  /var/www
