#!/bin/bash

# run npm build command against portfolio app
# appspec should have moved files into /home/ec2-user/portfolio

npm --prefix /home/ec2-user/portfolio run build

# copy build contents to www folder where nginx will look for it
# test deploy first before moving files
# mv /home/ec2-user/portfolio/build/*  /var/www/
